name: socar_dispatch_mobile
description: "AegisDispatch Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6

  # Networking & HTTP
  dio: ^5.7.0

  # Secure Local Storage
  flutter_secure_storage: ^9.2.2

  # Local Persistent Key-Value Storage
  shared_preferences: ^2.3.5

  # Image Picker & Caching
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Video Thumbnail & Temporary Storage
  path_provider: ^2.1.5


  # Location & Navigation
  geolocator: ^13.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  
  # External App Actions (Phone call, SMS, Mail)
  url_launcher: ^6.3.1
  
  # Background Telemetry & Service
  flutter_background_service: ^5.0.10

  # Real-Time SignalR WebSockets
  signalr_netcore: ^1.4.1

  # Push & Local Notifications
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1

  # Device Permissions
  permission_handler: ^11.4.0

  # UI, Fonts & SVG
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

  # Google Authentication
  google_sign_in: ^6.2.2
  flutter_video_thumbnail_plus: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/aegis_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/aegis_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
